### ISSUE TITLE
Assignment 1:

### ISSUE THREAD

**Issue by 54bit23** [vtcbca/basic-programming-64bit23#2]
can some one tell me how can i do this program in python.

**Comment by 64bit23** [comment]
The factorial of a non-negative integer ( n ) is the product of all positive integers less than or equal to ( n ). It is denoted as ( n! ).  
For example:  
\5! = 5 multi4 multi 3 multi 2 multi1 = 120 ).

**Comment by 54bit23** [comment]
yes I understand but can you tell me factorial of 4?

**Comment by 64bit23** [comment]
sing the formula:  

The factorial of 4 is 
(4! = 5  multi 4 multi 3 multi 2 multi 1 =  24.)

**Comment by 54bit23** [comment]
What data types can you use to store the factorial in the program?

**Comment by 64bit23** [comment]
In Python, we can use the following data types:  
1. int: For smaller numbers where the factorial fits within typical integer size.  
2. float: If the factorial value becomes very large and exceeds integer limits.  
3. string: If we need to store very large factorials and treat them as text.

**Comment by 54bit23** [comment]
How does the program handle negative numbers?

**Comment by 64bit23** [comment]
its too  easy   The program checks for negative input with the condition `if n < 0`. If true, it returns a message:  
"Factorial is not defined for negative numbers."

**Comment by 54bit23** [comment]
What is the time complexity of the factorial function in the program?

**Comment by 54bit23** [comment]
Why do we use a loop in the program to calculate the factorial?

**Comment by 64bit23** [comment]
A loop is used to multiply all integers from 2 to ( n ) iteratively. This avoids the overhead of recursion and is more efficient for larger values of ( n ).

---

**Comment by 64bit23** [comment]
ok thanks
