### ISSUE TITLE
Assignment-4 : Reverse String.

### ISSUE THREAD

**Issue by 54bit23** [vtcbca/basic-programming-64bit23#3]
How do you reverse a string using a for loop?

**Comment by 54bit23** [comment]
Use a loop to iterate through the string in reverse order:
python

```
reversed_string = ""
for char in string:
    reversed_string = char + reversed_string
```

**Comment by 64bit23** [comment]
Can you reverse a string without using slicing or a loop?

**Comment by 54bit23** [comment]
Yes, by using the reversed() function:

`reversed_string = ''.join(reversed(string))`

**Comment by 64bit23** [comment]
What happens if the input string is all spaces?

**Comment by 54bit23** [comment]
Reversing an all-space string will result in the same all-space string.

**Comment by 64bit23** [comment]
Can you reverse a string containing special characters?

**Comment by 54bit23** [comment]
Yes, special characters will also be reversed in their positions, like "abc#123" to "321#cba".

**Comment by 64bit23** [comment]
How do you reverse the words in a sentence while keeping the word order?

**Comment by 54bit23** [comment]
plit the string into words, reverse each word, and join them back:

`reversed_words = ' '.join([word[::-1] for word in string.split()])
`

**Comment by 64bit23** [comment]
Is the original string changed after reversing?

**Comment by 54bit23** [comment]
No, strings are immutable in Python. Reversing creates a new string without changing the original.

**Comment by 64bit23** [comment]
Use a loop to iterate through the string in reverse order:

```
reversed_string = ""
for char in string:
    reversed_string = char + reversed_string
```

**Comment by 54bit23** [comment]
Can you reverse a string without using slicing or a loop?

**Comment by 64bit23** [comment]
Yes, by using the reversed() function:

`reversed_string = ''.join(reversed(string))`

**Comment by 54bit23** [comment]
What happens if the input string is all spaces?

**Comment by 64bit23** [comment]
Reversing an all-space string will result in the same all-space string.

**Comment by 54bit23** [comment]
Can you reverse a string containing special characters?

**Comment by 64bit23** [comment]
Yes, special characters will also be reversed in their positions, like "abc#123" to "321#cba".

**Comment by 54bit23** [comment]
okay thanks for help
